on:
  workflow_dispatch:
    inputs:
      org:
        default: imjohnbo-org
        required: false
        description: "GitHub owner"

name: Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Happy path
    - uses: ./
      with:
        owner: ${{ github.event.inputs.org }}
        token: ${{ secrets.GITHUB_TOKEN }}
